.Dd October 7, 2023
.Dt SCHUTTING 4
.Os
.Sh NAME
.Nm schutting
.Nd Virtual fence device from the Netherlands
.Sh DESCRIPTION
The
.Nm
provides the perfect mechanism to store important data. 
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa /dev/schutting
.El
.Sh HISTORY
The original
.Nm
is written for GNU/Linux by Diederik de Zee.
The port to NetBSD is written by Thijs Haker.
